#!/usr/bin/env python3
"""Generate the SFDP ROM each device model carries.

The table is defined once, in cocotbext/ospi/sfdp.py, and emitted here as a
Verilog include. Generating it rather than hand-writing the bytes is what
keeps the model and the parser from drifting apart -- and the tests read
back through the parser exactly what this put in.

    python3 verilog/devices/generate_sfdp.py
"""

import importlib.util
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent.parent

spec = importlib.util.spec_from_file_location(
    "sfdp", ROOT / "cocotbext" / "ospi" / "sfdp.py"
)
sfdp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sfdp)

MB = 1024 * 1024

# Both parts: 512 Mb, 4-byte addressing only, DTR capable, 4 KB (0x21) and
# 64 KB (0xDC) erase, 256-byte pages.
COMMON_BFPT = dict(density_bits=512 * MB, address_bytes=sfdp.ADDR_4_ONLY,
                   dtr=True, page_size=256,
                   erase_types=((12, 0x21), (16, 0xDC)))

# Both parts are 4-byte-address only, and support read (0x13), page program
# (0x12) and both erase types with a 4-byte address. The 4BAIT is what tells
# a controller which opcode to use rather than leaving it to convert from
# the 3-byte set.
COMMON_4BAIT = dict(
    supported=(sfdp.FOURBAIT_READ | sfdp.FOURBAIT_PP |
               sfdp.FOURBAIT_ERASE_1 | sfdp.FOURBAIT_ERASE_2),
    erase_opcodes=(0x21, 0xDC),
)

DEVICES = {
    "mx25um51345g": dict(
        bfpt=COMMON_BFPT,
        # 8DTRD is the DTR octal read. Dummy cycles come from the
        # datasheet's "Dummy Cycle and Frequency Table": DC=000 gives 20
        # cycles at 200 MHz, DC=010 gives 16 at 173, DC=100 gives 12 at
        # 139, DC=101 gives 10 at 121. Each bin takes the count rated at
        # or above that speed.
        profile1=dict(fast_read_opcode=0xEE,
                      dummy_by_mhz={200: 20, 166: 16, 133: 12, 100: 10},
                      # RDSR grows a 4-byte address and 4 dummy cycles in OPI.
                      rdsr_dummy=4, rdsr_addr_bytes=4),
        fourbait=COMMON_4BAIT,
    ),
    "mt35xu512aba": dict(
        bfpt=COMMON_BFPT,
        # Linux programs 20 dummy cycles for this part's top speed and sets
        # rdsr_dummy = 8; RDSR takes no address bytes.
        profile1=dict(fast_read_opcode=0xFD,
                      dummy_by_mhz={200: 20, 166: 20, 133: 20, 100: 20},
                      rdsr_dummy=8, rdsr_addr_bytes=0),
        fourbait=COMMON_4BAIT,
    ),
}


def emit(name, params):
    image = sfdp.build_sfdp({
        sfdp.BFPT_ID: sfdp.build_bfpt(**params["bfpt"]),
        sfdp.PROFILE1_ID: sfdp.build_profile1(**params["profile1"]),
        sfdp.FOURBAIT_ID: sfdp.build_4bait(**params["fourbait"]),
    })
    lines = [
        f"// SFDP image for {name.upper()} -- generated by",
        "// verilog/devices/generate_sfdp.py from cocotbext/ospi/sfdp.py.",
        "// Do not edit by hand; regenerate instead.",
        "",
        f"localparam integer SFDP_BYTES = {len(image)};",
        "reg [7:0] sfdp [0:SFDP_BYTES-1];",
        "initial begin",
    ]
    for offset, byte in enumerate(image):
        lines.append(f"    sfdp[{offset:3d}] = 8'h{byte:02X};")
    lines.append("end")

    out = HERE / f"{name}_sfdp.vh"
    out.write_text("\n".join(lines) + "\n")
    print(f"  {out.name}: {len(image)} bytes")
    return image


if __name__ == "__main__":
    for name, params in DEVICES.items():
        emit(name, params)
