#!/usr/bin/env python3
"""Generate the SFDP ROM each device model carries.

The table is defined once, in cocotbext/ospi/sfdp.py, and emitted here as a
Verilog include. Generating it rather than hand-writing the bytes is what
keeps the model and the parser from drifting apart -- and the tests read
back through the parser exactly what this put in.

    python3 verilog/devices/generate_sfdp.py
"""

import importlib.util
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent.parent

spec = importlib.util.spec_from_file_location(
    "sfdp", ROOT / "cocotbext" / "ospi" / "sfdp.py"
)
sfdp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sfdp)

MB = 1024 * 1024

DEVICES = {
    # 512 Mb, 4-byte addressing only, DTR capable, 4 KB (0x21) and
    # 64 KB (0xDC) erase, 256-byte pages.
    "mx25um51345g": dict(density_bits=512 * MB, address_bytes=sfdp.ADDR_4_ONLY,
                         dtr=True, page_size=256,
                         erase_types=((12, 0x21), (16, 0xDC))),
    "mt35xu512aba": dict(density_bits=512 * MB, address_bytes=sfdp.ADDR_4_ONLY,
                         dtr=True, page_size=256,
                         erase_types=((12, 0x21), (16, 0xDC))),
}


def emit(name, params):
    image = sfdp.build_sfdp({sfdp.BFPT_ID: sfdp.build_bfpt(**params)})
    lines = [
        f"// SFDP image for {name.upper()} -- generated by",
        "// verilog/devices/generate_sfdp.py from cocotbext/ospi/sfdp.py.",
        "// Do not edit by hand; regenerate instead.",
        "",
        f"localparam integer SFDP_BYTES = {len(image)};",
        "reg [7:0] sfdp [0:SFDP_BYTES-1];",
        "initial begin",
    ]
    for offset, byte in enumerate(image):
        lines.append(f"    sfdp[{offset:3d}] = 8'h{byte:02X};")
    lines.append("end")

    out = HERE / f"{name}_sfdp.vh"
    out.write_text("\n".join(lines) + "\n")
    print(f"  {out.name}: {len(image)} bytes")
    return image


if __name__ == "__main__":
    for name, params in DEVICES.items():
        emit(name, params)
