# Macronix MX25UM51345G device model.
#
#   make -f Makefile.mx25

VERILOG_DIR := $(shell PYTHONPATH=$(shell pwd)/.. python3 -c \
    "import cocotbext.ospi as o; print(o.verilog_dir())" 2>/dev/null)
ifeq ($(VERILOG_DIR),)
VERILOG_DIR := $(shell pwd)/../cocotbext/ospi/verilog
endif

TOPLEVEL_LANG ?= verilog
SIM ?= icarus

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

SIM_BUILD = sim_build_mt35

TOPLEVEL = mt35xu512aba_test
MODULE   = test_mt35xu512aba

VERILOG_SOURCES  = $(VERILOG_DIR)/devices/mt35xu512aba.v
VERILOG_SOURCES += $(VERILOG_DIR)/devices/mt35xu512aba_test.v

export PYTHONPATH := $(shell pwd)/..:$(shell pwd):$(PYTHONPATH)
export COCOTB_HDL_TIMEUNIT
export COCOTB_HDL_TIMEPRECISION

# The SFDP ROM is an include next to the model.
COMPILE_ARGS += -I$(VERILOG_DIR)/devices

include $(shell cocotb-config --makefiles)/Makefile.sim

clean::
	@rm -rf $(SIM_BUILD) results.xml
