name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf gperf bison flex gtkwave
        wget https://github.com/steveicarus/iverilog/archive/refs/tags/v11_0.tar.gz
        tar -xvf v11_0.tar.gz
        cd iverilog-11_0
        sh autoconf.sh
        ./configure
        make
        sudo make install
        cd ..
        pip install cocotb

    - name: Run tests
      working-directory: tests
      run: make

