name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bison flex libreadline-dev gawk tcl-dev libffi-dev git \
                                graphviz xdot pkg-config python3 python3-pip libboost-system-dev \
                                libboost-python-dev libboost-context-dev autoconf gperf

    - name: Install Icarus Verilog
      run: |
        git clone https://github.com/steveicarus/iverilog.git
        cd iverilog
        sh autoconf.sh
        ./configure
        make
        sudo make install

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip install cocotb

    - name: Add cocotbext to PYTHONPATH and run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: make -C tests


